//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cstapp
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
        public string Name { get; set; }
        public string IdNo { get; set; }
        public string State { get; set; }
        public string Tel { get; set; }
        public string Contest { get; set; }
    }
}
