//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loc_markes
    {
        public int Id { get; set; }
        public Nullable<int> locId { get; set; }
        public string lat { get; set; }
        public string log { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public Nullable<int> display { get; set; }
    
        public virtual loc loc { get; set; }
    }
}
