//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salalahDBEntities : DbContext
    {
        public salalahDBEntities()
            : base("name=salalahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cusInfo> cusInfoes { get; set; }
        public virtual DbSet<loc> locs { get; set; }
        public virtual DbSet<loc_markes> loc_markes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_adv_cats> tbl_adv_cats { get; set; }
        public virtual DbSet<tbl_cats> tbl_cats { get; set; }
        public virtual DbSet<tbl_gust_Answers> tbl_gust_Answers { get; set; }
        public virtual DbSet<tbl_Images> tbl_Images { get; set; }
        public virtual DbSet<tbl_mainnews> tbl_mainnews { get; set; }
        public virtual DbSet<tbl_menu> tbl_menu { get; set; }
        public virtual DbSet<tbl_quize> tbl_quize { get; set; }
        public virtual DbSet<tbl_Rss> tbl_Rss { get; set; }
        public virtual DbSet<tbl_websettings_cats> tbl_websettings_cats { get; set; }
        public virtual DbSet<tbl_winners> tbl_winners { get; set; }
        public virtual DbSet<tbl_articles> tbl_articles { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_images1> tbl_images1 { get; set; }
        public virtual DbSet<tbl_mainsections> tbl_mainsections { get; set; }
        public virtual DbSet<tbl_siteSections> tbl_siteSections { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_posts> tbl_posts { get; set; }
        public virtual DbSet<cstapp> cstapps { get; set; }
    }
}
