//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_winners
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> g_date { get; set; }
        public string g_name { get; set; }
        public string g_email { get; set; }
        public string g_tel { get; set; }
        public Nullable<int> q_no { get; set; }
        public Nullable<int> q_ans { get; set; }
    }
}
