//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cats
    {
        public int Id { get; set; }
        public string cat_desc { get; set; }
        public string cat_summary { get; set; }
        public Nullable<bool> cat_show { get; set; }
        public Nullable<int> cat_order { get; set; }
    }
}
