//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mainnews
    {
        public int Id { get; set; }
        public Nullable<int> Npost_pid { get; set; }
        public Nullable<int> Npost_catid { get; set; }
        public Nullable<int> Npost_order { get; set; }
        public Nullable<int> Npost_type { get; set; }
        public Nullable<int> Npost_postion { get; set; }
        public Nullable<int> Npost_TabLoc { get; set; }
        public Nullable<int> Npost_show { get; set; }
        public Nullable<System.DateTime> Npost_date { get; set; }
    }
}
