//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siteSections
    {
        public int secId { get; set; }
        public string sec_title { get; set; }
        public string sec_lock { get; set; }
        public string sec_desc { get; set; }
        public Nullable<int> sec_status { get; set; }
    }
}
