//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_articles
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public string a_title { get; set; }
        public string a_source { get; set; }
        public string a_desc { get; set; }
        public string a_link { get; set; }
        public string a_img { get; set; }
        public string a_type { get; set; }
        public string a_mediatype { get; set; }
        public string a_mediatype_link { get; set; }
        public Nullable<int> a_order { get; set; }
        public string a_loc { get; set; }
        public string a_status { get; set; }
    }
}
