//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu
    {
        public int menu_item_id { get; set; }
        public string menu_item_name { get; set; }
        public string menu_item_link { get; set; }
        public string menu_item_target { get; set; }
        public Nullable<int> parent_item_id { get; set; }
        public Nullable<int> menu_item_order { get; set; }
        public string lang { get; set; }
    }
}
