//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_posts
    {
        public int Id { get; set; }
        public Nullable<int> post_auid { get; set; }
        public string post_title { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string post_content { get; set; }
        public string post_excerpt { get; set; }
        public string post_catid { get; set; }
        public Nullable<System.DateTime> post_modified { get; set; }
        public Nullable<int> post_status { get; set; }
        public Nullable<int> post_parent { get; set; }
        public Nullable<int> post_menu_order { get; set; }
        public string post_img { get; set; }
        public string post_price { get; set; }
    }
}
