//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_quize
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> q_date { get; set; }
        public Nullable<int> q_no { get; set; }
        public string q_question { get; set; }
        public string q_ans1 { get; set; }
        public string q_ans2 { get; set; }
        public string q_ans3 { get; set; }
        public string q_ans4 { get; set; }
        public Nullable<int> q_corr { get; set; }
        public string q_img { get; set; }
        public Nullable<int> q_img_show { get; set; }
    }
}
