//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_contact
    {
        public int id { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string GName { get; set; }
        public string GAddress { get; set; }
        public string GEmail { get; set; }
        public string GSubject { get; set; }
        public string GData { get; set; }
    }
}
