//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rss
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datepublished { get; set; }
    }
}
