//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalFestival2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adv_cats
    {
        public int Id { get; set; }
        public string adv_cat_title { get; set; }
        public string adv_cat_img { get; set; }
        public string adv_cat_desc { get; set; }
        public string adv_cat_lnk { get; set; }
        public string type { get; set; }
        public Nullable<int> display { get; set; }
    }
}
